### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by nsklikas** [canonical/glauth-utils#13]
Something causes the CI to fail, I am unable to reproduce this locally. Perhaps the problem is that the charm goes into an error state when deployed, but when we call `wait_for_idle` we don't set the `raise_on_error` flag to `False`. Of course this does not explain why deploying the glauth charm fails when running on this repo, but not on the glauth repo.

See https://github.com/canonical/glauth-utils/actions/runs/8748968457/job/24189969377

**Comment by wood-push-melon** [comment]
Fixed in https://github.com/canonical/glauth-utils/pull/15
